2024-11-06 22:21:12.250787: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-06 22:21:12.250851: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-06 22:21:12.250851: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-06 22:21:12.250910: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-06 22:21:12.250986: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-06 22:21:12.251050: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-06 22:21:12.251168: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-06 22:21:12.251233: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-06 22:21:12.251864: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-06 22:21:12.251853: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-06 22:21:12.251965: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-06 22:21:12.252166: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-06 22:21:13.554214: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-11-06 22:21:13.554319: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-11-06 22:21:13.554304: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-11-06 22:21:13.554345: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
usage: inference_ddp.py
       [-h]
       [--epochs EPOCHS]
       [--resume_from_checkpoint RESUME_FROM_CHECKPOINT]
       [--offline_model_path OFFLINE_MODEL_PATH]
       [--seed SEED]
       [--data DATA]
       [--task_name TASK_NAME]
       [--batch_size_val BATCH_SIZE_VAL]
       [--dev_filepath DEV_FILEPATH]
       [--test_filepath TEST_FILEPATH]
       [--output_filepath OUTPUT_FILEPATH]
       [--model_name MODEL_NAME]
       [--embedding_size EMBEDDING_SIZE]
       [--max_length MAX_LENGTH]
usage: inference_ddp.py
       [-h]
       [--epochs EPOCHS]
       [--resume_from_checkpoint RESUME_FROM_CHECKPOINT]
       [--offline_model_path OFFLINE_MODEL_PATH]
       [--seed SEED]
       [--data DATA]
       [--task_name TASK_NAME]
       [--batch_size_val BATCH_SIZE_VAL]
       [--dev_filepath DEV_FILEPATH]
       [--test_filepath TEST_FILEPATH]
       [--output_filepath OUTPUT_FILEPATH]
       [--model_name MODEL_NAME]
       [--embedding_size EMBEDDING_SIZE]
       [--max_length MAX_LENGTH]
usage: inference_ddp.py
       [-h]
       [--epochs EPOCHS]
       [--resume_from_checkpoint RESUME_FROM_CHECKPOINT]
       [--offline_model_path OFFLINE_MODEL_PATH]
       [--seed SEED]
       [--data DATA]
       [--task_name TASK_NAME]
       [--batch_size_val BATCH_SIZE_VAL]
       [--dev_filepath DEV_FILEPATH]
       [--test_filepath TEST_FILEPATH]
       [--output_filepath OUTPUT_FILEPATH]
       [--model_name MODEL_NAME]
       [--embedding_size EMBEDDING_SIZE]
       [--max_length MAX_LENGTH]
inference_ddp.py: error: unrecognized arguments: --gradient_accumulation_steps 2
usage: inference_ddp.py
       [-h]
       [--epochs EPOCHS]
       [--resume_from_checkpoint RESUME_FROM_CHECKPOINT]
       [--offline_model_path OFFLINE_MODEL_PATH]
       [--seed SEED]
       [--data DATA]
       [--task_name TASK_NAME]
       [--batch_size_val BATCH_SIZE_VAL]
       [--dev_filepath DEV_FILEPATH]
       [--test_filepath TEST_FILEPATH]
       [--output_filepath OUTPUT_FILEPATH]
       [--model_name MODEL_NAME]
       [--embedding_size EMBEDDING_SIZE]
       [--max_length MAX_LENGTH]
inference_ddp.py: error: unrecognized arguments: --gradient_accumulation_steps 2
inference_ddp.py: error: unrecognized arguments: --gradient_accumulation_steps 2
inference_ddp.py: error: unrecognized arguments: --gradient_accumulation_steps 2
srun: error: gpu102: tasks 0-3: Exited with exit code 2
