2024-11-06 22:23:07.219833: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-06 22:23:07.219900: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-06 22:23:07.220193: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-06 22:23:07.220271: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-06 22:23:07.220877: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-06 22:23:07.220951: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-06 22:23:07.221016: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-06 22:23:07.221435: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-06 22:23:07.221594: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-06 22:23:07.221657: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-06 22:23:07.222166: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-06 22:23:07.222589: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-06 22:23:08.474112: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-11-06 22:23:08.474151: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-11-06 22:23:08.474216: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-11-06 22:23:08.474265: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
usage: inference_ddp.py
       [-h]
       [--epochs EPOCHS]
       [--resume_from_checkpoint RESUME_FROM_CHECKPOINT]
       [--offline_model_path OFFLINE_MODEL_PATH]
       [--seed SEED]
       [--data DATA]
       [--task_name TASK_NAME]
       [--batch_size_val BATCH_SIZE_VAL]
       [--dev_filepath DEV_FILEPATH]
       [--test_filepath TEST_FILEPATH]
       [--output_filepath OUTPUT_FILEPATH]
       [--model_name MODEL_NAME]
       [--embedding_size EMBEDDING_SIZE]
       [--max_length MAX_LENGTH]
usage: inference_ddp.py
       [-h]
       [--epochs EPOCHS]
       [--resume_from_checkpoint RESUME_FROM_CHECKPOINT]
       [--offline_model_path OFFLINE_MODEL_PATH]
       [--seed SEED]
       [--data DATA]
       [--task_name TASK_NAME]
       [--batch_size_val BATCH_SIZE_VAL]
       [--dev_filepath DEV_FILEPATH]
       [--test_filepath TEST_FILEPATH]
       [--output_filepath OUTPUT_FILEPATH]
       [--model_name MODEL_NAME]
       [--embedding_size EMBEDDING_SIZE]
       [--max_length MAX_LENGTH]
usage: inference_ddp.py
       [-h]
       [--epochs EPOCHS]
       [--resume_from_checkpoint RESUME_FROM_CHECKPOINT]
       [--offline_model_path OFFLINE_MODEL_PATH]
       [--seed SEED]
       [--data DATA]
       [--task_name TASK_NAME]
       [--batch_size_val BATCH_SIZE_VAL]
       [--dev_filepath DEV_FILEPATH]
       [--test_filepath TEST_FILEPATH]
       [--output_filepath OUTPUT_FILEPATH]
       [--model_name MODEL_NAME]
       [--embedding_size EMBEDDING_SIZE]
       [--max_length MAX_LENGTH]
inference_ddp.py: error: unrecognized arguments: --gradient_accumulation_steps 2
inference_ddp.py: error: unrecognized arguments: --gradient_accumulation_steps 2
usage: inference_ddp.py
       [-h]
       [--epochs EPOCHS]
       [--resume_from_checkpoint RESUME_FROM_CHECKPOINT]
       [--offline_model_path OFFLINE_MODEL_PATH]
       [--seed SEED]
       [--data DATA]
       [--task_name TASK_NAME]
       [--batch_size_val BATCH_SIZE_VAL]
       [--dev_filepath DEV_FILEPATH]
       [--test_filepath TEST_FILEPATH]
       [--output_filepath OUTPUT_FILEPATH]
       [--model_name MODEL_NAME]
       [--embedding_size EMBEDDING_SIZE]
       [--max_length MAX_LENGTH]
inference_ddp.py: error: unrecognized arguments: --gradient_accumulation_steps 2
inference_ddp.py: error: unrecognized arguments: --gradient_accumulation_steps 2
srun: error: gpu102: tasks 0-3: Exited with exit code 2
